### ISSUE TITLE
Migration fails due to attachment version

### ISSUE THREAD

**Issue by FabianMauz** [ComPlat/chemotion_ELN#1039]
Migration from Version 1.4.x to current dev-5 branch failed. 

The migration fails because the gem ancestry tries to split content of a db column which is defined as integer. 
 [20210825082859 AddAttachmentDataToAttachments](https://github.com/ComPlat/chemotion_ELN/commit/b853ce0724b89fbe783454fded1707fed654d6ed) 

In a later migration file, the column type is changed to string.
[20211116000000_change_version_type_from_attachment.rb](https://github.com/ComPlat/chemotion_ELN/commit/b853ce0724b89fbe783454fded1707fed654d6ed#diff-19cb6d04db9b42e0e1c5e95b2eeaf2e1856f3c3c6e28ff1505f394f0719ff86d)

Question: Why is ancestry used in attachments (versioning, reflect the editing path )?

Error log from migration:

== 20210825082859 AddAttachmentDataToAttachments: migrating ===================
-- add_column(:attachments, :attachment_data, :jsonb)
   -> 0.0097s
== 20210825082859 AddAttachmentDataToAttachments: migrated (0.0099s) ==========

== 20210921114428 UpdateAttachmentsWithShrine: migrating ======================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `split' for 0:Integer
/home/chemotion-dev/app/db/migrate/20210921114428_update_attachments_with_shrine.rb:14:in `block in change'
/home/chemotion-dev/app/db/migrate/20210921114428_update_attachments_with_shrine.rb:3:in `change'
bin/rails:4:in `<main>'

Caused by:
NoMethodError: undefined method `split' for 0:Integer
/home/chemotion-dev/app/db/migrate/20210921114428_update_attachments_with_shrine.rb:14:in `block in change'
/home/chemotion-dev/app/db/migrate/20210921114428_update_attachments_with_shrine.rb:3:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by PiTrem** [comment]
resolved with 4535b3513  + 6903c1bab
