### ISSUE TITLE
Disabled Sign Up breaks Shibboleth Login

### ISSUE THREAD

**Issue by crsoph** [ComPlat/chemotion_ELN#1334]
- I am a system/ELN admin

We are running/testing Chemotion ELN Version 1.6.0 with Shibboleth Login configured.
We want our users to exclusively use their University credentials via Shibboleth for logging in, without manually creating local accounts.
We therefore set `DEVISE_DISABLED_SIGN_UP='true'` in the .env file.

# Expected Behavior

Manual Sign Up is disabled.

# Current Behavior

No user (not even existing ones) can log in via Shibboleth.

# Failure Information 

The user is displayed an error page (Error 404).

## Failure Logs / Screenshots

Docker Logs from the ELN container:

```
2023-05-31 08:05:21 +0000, [INFO]: [chemotion-test.rz] [d82db782-f6a5-4c18-90ef-7cee4eb7a69a] Started GET "/users/auth/shibboleth" for <REDACTED_IP> at 2023-05-31 08:05:21 +0000 
I, [2023-05-31T08:05:21.454004 #6]  INFO -- omniauth: (shibboleth) Request phase initiated.
2023-05-31 08:05:21 +0000, [INFO]: [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] Started GET "/users/auth/shibboleth/callback" for <REDACTED_IP> at 2023-05-31 08:05:21 +0000 
I, [2023-05-31T08:05:21.469791 #6]  INFO -- omniauth: (shibboleth) Callback phase initiated.
2023-05-31 08:05:21 +0000, [FATAL]: [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0]    | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] AbstractController::ActionNotFound (The action 'shibboleth' could not be found for Devise::OmniauthCallbacksController | Did you mean?  failure |                passthru): | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0]    | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/abstract_controller/base.rb:160:in `process' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionview (6.1.7.3) lib/action_view/rendering.rb:39:in `process' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_controller/metal.rb:190:in `dispatch' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_controller/metal.rb:254:in `dispatch' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/routing/route_set.rb:33:in `serve' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/routing/mapper.rb:49:in `serve' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/journey/router.rb:50:in `block in serve' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/journey/router.rb:32:in `each' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/journey/router.rb:32:in `serve' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/routing/route_set.rb:842:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth (1.9.2) lib/omniauth/strategy.rb:420:in `call_app!' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth (1.9.2) lib/omniauth/strategy.rb:373:in `callback_phase' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth-shibboleth (1.3.0) lib/omniauth/strategies/shibboleth.rb:75:in `callback_phase' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth (1.9.2) lib/omniauth/strategy.rb:238:in `callback_call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth (1.9.2) lib/omniauth/strategy.rb:189:in `call!' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] omniauth (1.9.2) lib/omniauth/strategy.rb:169:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] warden (1.2.9) lib/warden/manager.rb:36:in `block in call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] warden (1.2.9) lib/warden/manager.rb:34:in `catch' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] warden (1.2.9) lib/warden/manager.rb:34:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/tempfile_reaper.rb:15:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/etag.rb:27:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/conditional_get.rb:27:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/head.rb:12:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/http/permissions_policy.rb:22:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/http/content_security_policy.rb:19:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/session/abstract/id.rb:266:in `context' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/session/abstract/id.rb:260:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/cookies.rb:697:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] activesupport (6.1.7.3) lib/active_support/callbacks.rb:98:in `run_callbacks' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-rails (5.5.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry/hub.rb:199:in `with_session_tracking' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry-ruby.rb:374:in `with_session_tracking' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry/rack/capture_exceptions.rb:19:in `block in call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry/hub.rb:59:in `with_scope' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry-ruby.rb:354:in `with_scope' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] sentry-ruby (5.5.0) lib/sentry/rack/capture_exceptions.rb:18:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] railties (6.1.7.3) lib/rails/rack/logger.rb:37:in `call_app' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] railties (6.1.7.3) lib/rails/rack/logger.rb:26:in `block in call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] activesupport (6.1.7.3) lib/active_support/tagged_logging.rb:99:in `block in tagged' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] activesupport (6.1.7.3) lib/active_support/tagged_logging.rb:37:in `tagged' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] activesupport (6.1.7.3) lib/active_support/tagged_logging.rb:99:in `tagged' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] railties (6.1.7.3) lib/rails/rack/logger.rb:26:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/request_id.rb:26:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/method_override.rb:24:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/runtime.rb:22:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] activesupport (6.1.7.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/executor.rb:14:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/static.rb:24:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/static.rb:24:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] rack (2.2.6.4) lib/rack/sendfile.rb:110:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] actionpack (6.1.7.3) lib/action_dispatch/middleware/host_authorization.rb:142:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] railties (6.1.7.3) lib/rails/engine.rb:539:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/configuration.rb:252:in `call' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/request.rb:76:in `handle_request' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/server.rb:443:in `process_client' | [chemotion-test.rz] [c7f55e85-b4be-49ad-8ca7-50e0eec5c6b0] puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

It appears that the Shibboleth Plugin/Controller(?) is not loaded.

**Comment by phuang26** [comment]
@crsoph  the DEVISE_DISABLED_SIGN_UP setting has disabled the entire sign-up function. Therefore, I will create a new ticket referencing our discussion from last week and close this one.

**Comment by phuang26** [comment]
@crsoph , hi Christoph, this feature has been included in ELN v1.7.0, please refer to:
https://www.chemotion.net/docs/eln/admin/features#user-authentication-userprovider "extra rules".
