### ISSUE TITLE
Cannot create collection after uprage to 1.7.2 and restore of backup

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_ELN#1540]
- I am a system/ELN admin

# Expected Behavior

Collections from old installations are available in new installation.
AND
Manage & organize collections -> create collection by hitting "+" -> Save -> new collection saved. Yeah!

# Current Behavior

Collections from old installation are not available in new installation.
AND
Manage & organize collections -> (no collection there ->) create collection by hitting "+" -> Save -> all gone again! Oh no! -> try again -> same.

 - OS: [Windows 11 most recent or macOS 10.15.17]
 - Chrome Browser 

## Context

Somewhere, Chemotion 1.6.0 was running and the admin decided to upgrade to 1.7.2. Stuff outside of docker volumes (services and share) is backed up separately on a regular basis and a cronjob daily runs:

`docker compose run eln chemotion backup`
...to get the  backup.sql.gz and backup.data.tar.gz, which is also backed up somewhere. Then:

`docker compose down --remove-orphans`
`docker volume rm chemotion_app`
..to get rid of the old installation

`wget https://raw.githubusercontent.com/Chemotion/ChemCLI/main/payload/docker-compose.yml` and diffed with the previous docker-compose.yaml from v1.6.0
`docker compose up --no-start`
`docker compose up -d`
...to get Chemotion 1.7.2

`docker compose down --remove-orphans` and copied the backup backup.sql.gz and backup.data.tar.gz to folder where with docker compose file is, then:
`docker compose run eln chemotion restore`
...to restore all user data and data.

The sysadmin could login and all user were recovered. However, user cannot see their collections and cannot create a new collection. 

Help highly appreciated!

**Comment by PiTrem** [comment]
you might have to force a db reset

```sh
docker compose run eln chemotion restore --force-db-reset
```

or using the CLI

```sh
./chemCLI instance restore --name <instance_name> --data /home/user/absolute/path/backup-xxxxxx-xxxxxx.data.tar.gz --db /home/user/absolute/path/backup/backup-xxxxxx-xxxxxx.sql.gz --address https://<address>
```

**Comment by harivyasi** [comment]
To add to what @PiTrem said, if the restore is going as intended, you should see the following messages when restoring the database:
```
Running task: [restore]
[restore] DB authentication successful.
[restore] Old database not present. Nothing to delete.
[restore] DB not found. Trying to create it.
[restore] Database ready.
[restore] Database restoration finished successfully.
```

**Comment by tilfischer** [comment]
Thank you for your help!

```
someuser@somehost:~> docker compose run eln chemotion restore --force-db-reset
[+] Creating 3/0
 ✔ Container vmiocak_zeitler_chemotion-db-1         Running                                                                              0.0s 
 ✔ Container vmiocak_zeitler_chemotion-msconvert-1  Running                                                                              0.0s 
 ✔ Container vmiocak_zeitler_chemotion-spectra-1    Running                                                                              0.0s 
Running task: [restore]
[restore] DB authentication successful.
[restore] Database ready.
[restore] Database restoration finished successfully.
[restore] File restoration finished successfully.
Command finished successfully.
Duration: 6s
Task [restore] finished.
```

However, running `docker compose exec eln bundle exec rails db:migrate` as suggested by Pierre gives

```
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued PubchemCidJob (Job ID: c15929dc-29d9-401f-b666-05635149add8) to DelayedJob(pubchem) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued PubchemLcssJob (Job ID: 51058bf5-2cb5-43d0-8100-648b9a3f49c3) to DelayedJob(pubchemLcss) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued RefreshElementTagJob (Job ID: baa650f0-3c18-4c6c-9110-cf3aa18d0eab) to DelayedJob(refresh_element_tag) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued ChemrepoIdJob (Job ID: ea8b65d5-ffd7-430e-b0c5-300c5206c639) to DelayedJob(chemrepo_id_job) 
2023-09-26 07:03:12 +0000, [INFO]: Render service configured at: http://ketchersvc:4000/render 
2023-09-26 07:03:12 +0000, [INFO]: Chemspectra endpoint is configured to be 'http://spectra:4000'. 
2023-09-26 07:03:12 +0000, [INFO]: NMRiumWrapper endpoint configured to be 'https://nmrium.nmrxiv.org/releases/v0.1.0/'. 
2023-09-26 07:03:12 +0000, [INFO]: Migrating to CreateChemicals (20221024150829) 
== 20221024150829 CreateChemicals: migrating ==================================
-- create_table(:chemicals, {})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Best,
Tillmann

**Comment by tilfischer** [comment]
Thank you for your help!

```
someuser@somehost:~> docker compose run eln chemotion restore --force-db-reset
[+] Creating 3/0
 ✔ Container someuser-db-1         Running                                                                              0.0s 
 ✔ Container someuser-msconvert-1  Running                                                                              0.0s 
 ✔ Container someuser-spectra-1    Running                                                                              0.0s 
Running task: [restore]
[restore] DB authentication successful.
[restore] Database ready.
[restore] Database restoration finished successfully.
[restore] File restoration finished successfully.
Command finished successfully.
Duration: 6s
Task [restore] finished.
```

However, running `docker compose exec eln bundle exec rails db:migrate` as suggested by Pierre gives

```
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued PubchemCidJob (Job ID: c15929dc-29d9-401f-b666-05635149add8) to DelayedJob(pubchem) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued PubchemLcssJob (Job ID: 51058bf5-2cb5-43d0-8100-648b9a3f49c3) to DelayedJob(pubchemLcss) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued RefreshElementTagJob (Job ID: baa650f0-3c18-4c6c-9110-cf3aa18d0eab) to DelayedJob(refresh_element_tag) 
2023-09-26 07:03:12 +0000, [INFO]: [ActiveJob] Enqueued ChemrepoIdJob (Job ID: ea8b65d5-ffd7-430e-b0c5-300c5206c639) to DelayedJob(chemrepo_id_job) 
2023-09-26 07:03:12 +0000, [INFO]: Render service configured at: http://ketchersvc:4000/render 
2023-09-26 07:03:12 +0000, [INFO]: Chemspectra endpoint is configured to be 'http://spectra:4000'. 
2023-09-26 07:03:12 +0000, [INFO]: NMRiumWrapper endpoint configured to be 'https://nmrium.nmrxiv.org/releases/v0.1.0/'. 
2023-09-26 07:03:12 +0000, [INFO]: Migrating to CreateChemicals (20221024150829) 
== 20221024150829 CreateChemicals: migrating ==================================
-- create_table(:chemicals, {})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Best,
Tillmann

**Comment by harivyasi** [comment]
Hi,

@tilfischer did you check the instance after the `restore` command but before running the `migrations`?

-Shashank

**Comment by PiTrem** [comment]
@tilfischer  

sorry, the flag seems to not work  because there is no explicit warning about resetting the DB.

Instead of ~~docker compose run eln chemotion restore --force-db-reset~~ , can you try :


docker compose run -e FORCE_DB_RESET=1 eln chemotion restore

**Comment by tilfischer** [comment]
```
someuser@somehosst:~> docker compose run -e FORCE_DB_RESET=1 eln chemotion restore 
[+] Creating 3/0
 ✔ Container someuser-msconvert-1  Running                0.0s 
 ✔ Container someuser_chemotion-spectra-1    Running                0.0s 
 ✔ Container someuser_chemotion-db-1         Running                0.0s 
Running task: [restore]
[restore] DB authentication successful.
[restore] Database reset enforced. [chemotion] will be dropped!
DROP DATABASE
[restore] DB not found. Trying to create it.
[restore] Database ready.
[restore] Database restoration finished successfully.
[restore] File restoration finished successfully.
Command finished successfully.
Duration: 14s
Task [restore] finished.
```

```
someuser@somehost:~> docker compose exec eln bundle exec rails db:migrate
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
2023-09-26 08:52:19 +0000, [INFO]: [ActiveJob] Enqueued PubchemCidJob (Job ID: 889493ea-9e22-4c9f-826b-d54c860d5312) to DelayedJob(pubchem) 
2023-09-26 08:52:19 +0000, [INFO]: [ActiveJob] Enqueued PubchemLcssJob (Job ID: 6fb80a1c-1493-4a89-a5aa-d4938f6cdf26) to DelayedJob(pubchemLcss) 
2023-09-26 08:52:19 +0000, [INFO]: [ActiveJob] Enqueued RefreshElementTagJob (Job ID: c8225904-bb8e-4d0f-8fc8-0e309c38a7cc) to DelayedJob(refresh_element_tag) 
2023-09-26 08:52:19 +0000, [INFO]: [ActiveJob] Enqueued ChemrepoIdJob (Job ID: fddbfece-7898-4fa9-a709-91579ba7da8e) to DelayedJob(chemrepo_id_job) 
2023-09-26 08:52:19 +0000, [INFO]: Render service configured at: http://ketchersvc:4000/render 
2023-09-26 08:52:19 +0000, [INFO]: Chemspectra endpoint is configured to be 'http://spectra:4000'. 
2023-09-26 08:52:19 +0000, [INFO]: NMRiumWrapper endpoint configured to be 'https://nmrium.nmrxiv.org/releases/v0.1.0/'. 
2023-09-26 08:52:20 +0000, [INFO]: Migrating to CreateChemicals (20221024150829) 
== 20221024150829 CreateChemicals: migrating ==================================
-- create_table(:chemicals, {})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "chemicals" already exists
/chemotion/app/db/migrate/20221024150829_create_chemicals.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by tilfischer** [comment]
Solved. Thanks to @FabianMauz  After login to psql with `psql postgres postgres` and connecting with chemotion `\c chemotion` we dropped the following tables

```
drop table chemicals
drop table calendar_entries
drop table calendar_entry_notifications
```

followed by `docker compose exec eln bundle exec rails db:migrate` gave

```
someuser@somehost:~> docker compose exec eln bundle exec rails db:migrate
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/asdf/installs/ruby/2.7.8/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/cache/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
2023-09-28 12:25:52 +0000, [INFO]: [ActiveJob] Enqueued PubchemCidJob (Job ID: cb9978e6-5dd7-4179-a527-4089685f882e) to DelayedJob(pubchem)
2023-09-28 12:25:52 +0000, [INFO]: [ActiveJob] Enqueued PubchemLcssJob (Job ID: bcf7eacf-b491-4f2b-a99b-3c674fdd84c5) to DelayedJob(pubchemLcss)
2023-09-28 12:25:52 +0000, [INFO]: [ActiveJob] Enqueued RefreshElementTagJob (Job ID: ab1eaecf-d2bc-40e1-a453-debd5a30ae89) to DelayedJob(refresh_element_tag)
2023-09-28 12:25:52 +0000, [INFO]: [ActiveJob] Enqueued ChemrepoIdJob (Job ID: a0911e0f-da2a-4bda-ae35-9da9e64c8cf4) to DelayedJob(chemrepo_id_job)
2023-09-28 12:25:52 +0000, [INFO]: Render service configured at: http://ketchersvc:4000/render
2023-09-28 12:25:52 +0000, [INFO]: Chemspectra endpoint is configured to be 'http://spectra:4000'.
2023-09-28 12:25:52 +0000, [INFO]: NMRiumWrapper endpoint configured to be 'https://nmrium.nmrxiv.org/releases/v0.1.0/'.
2023-09-28 12:25:52 +0000, [INFO]: Migrating to CreateCalendarEntryNotifications (20230210124435)
== 20230210124435 CreateCalendarEntryNotifications: migrating =================
-- create_table(:calendar_entry_notifications)
   -> 0.0232s
== 20230210124435 CreateCalendarEntryNotifications: migrated (0.0233s) ========

2023-09-28 12:25:52 +0000, [INFO]: Migrating to MatriceComment (20230420121233)
== 20230420121233 MatriceComment: migrating ===================================
== 20230420121233 MatriceComment: migrated (0.1744s) ==========================

2023-09-28 12:25:53 +0000, [INFO]: Migrating to AddSamplesImportChannel (20230531142756)
== 20230531142756 AddSamplesImportChannel: migrating ==========================
== 20230531142756 AddSamplesImportChannel: migrated (0.0117s) =================

2023-09-28 12:25:53 +0000, [INFO]: Migrating to UpdateCommentChannel (20230613063121)
== 20230613063121 UpdateCommentChannel: migrating =============================
== 20230613063121 UpdateCommentChannel: migrated (0.0033s) ====================
```
