### ISSUE TITLE
Reaction Variations: Update variations' sample IDs when reaction is copied

### ISSUE THREAD

**Issue by JanCBrammer** [ComPlat/chemotion_ELN#2264]
Once a reaction is copied, the samples of the copied reaction get new IDs.

When the reaction has variations, those get copied as well.
However, the variations keep a reference to the original sample IDs instead of the copied IDs.

When the copied variations try to retrieve the samples based on the copied IDs, the table crashes with

```
TypeError: Cannot read properties of undefined (reading 'mass')
    at Object.MaterialFormatter [as valueFormatter] (ReactionVariationsComponents.js:94:1)
    at main.esm.mjs:36384:1
    at ValueService.formatValue (main.esm.mjs:42549:1)
    at _CellCtrl.callValueFormatter (main.esm.mjs:25019:1)
    at _CellCtrl.updateAndFormatValue (main.esm.mjs:25025:1)
    at new _CellCtrl (main.esm.mjs:24586:1)
    at main.esm.mjs:25661:1
    at Array.forEach (<anonymous>)
    at _RowCtrl.createCellCtrls (main.esm.mjs:25657:1)
    at _RowCtrl.createAllCellCtrls (main.esm.mjs:25711:1)
```

~~To prevent ID inconsistencies for copied variations, the variations should be empty on copying a reaction.
Conceptually, by not copying the variations we're following what's being done with analyses which aren't copied either.
The latter is a good default since copying the variations might not be intended.~~

**Comment by JanCBrammer** [comment]
Thanks for the feedback @FabianFink. I'll add an option to copy the variations along with the reaction.
