### ISSUE TITLE
Installation script fails at Capistrano deploy stage

### ISSUE THREAD

**Issue by jdnicholas** [ComPlat/chemotion_ELN#359]
I attempted to install on a Ubuntu 18.04 server running on VirtualBox using the installation script as described here: https://github.com/ComPlat/chemotion_ELN/blob/development/INSTALL.md but get the message "An error has occured" during the Capistrano deploy stage.

The code running appears as below:

```
01:22 deploy:migrating
      01 /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.5.6 do bundle exec rake db:migrate
      01 Now using node v12.16.1 (npm v6.13.7)
      01 rake aborted!
      01 LoadError: cannot load such file -- /home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/rdkit/Code/lib/RDKitChem
      01 /home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `require_relative'
      01 /home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `<top (required)>'
      01 /var/www/chemotion_ELN/releases/20200503174904/config/application.rb:18:in `<top (required)>'
      01 /var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `require'
      01 /var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `<top (required)>'
      01 /home/production/.rvm/gems/ruby-2.5.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
      01 /home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `eval'
      01 /home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `<main>'
      01 (See full trace by running task with --trace)
```

and later on

<details>
  <summary>Deploy failed code</summary>

```
** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [f39b2619] Finished in 2.334 seconds with exit status 0 (successful).

  INFO The Gemfile's dependencies are satisfied, skipping installation

  INFO [deploy:migrate] Run `rake db:migrate`

 DEBUG [70435082] Running if test ! -d /var/www/chemotion_ELN/releases/20200503174904; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20200503174904'" 1>&2; false; fi as production@localhost

 DEBUG [70435082] Command: if test ! -d /var/www/chemotion_ELN/releases/20200503174904; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20200503174904'" 1>&2; false; fi

 DEBUG [087bae83] Finished in 0.042 seconds with exit status 0 (successful).

  INFO [5c8b6d67] Running /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.5.6 do bundle exec rake db:migrate as production@localhost

 DEBUG [5c8b6d67] Command: cd /var/www/chemotion_ELN/releases/20200503174904 && ( export NODE_VERSION="v12.16.1" RAILS_ENV="production" ; /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.5.6 do bundle exec rake db:migrate )

 DEBUG [54da2d1a] 	Now using node v12.16.1 (npm v6.13.7)

 DEBUG [54da2d1a] 	rake aborted!

 DEBUG [54da2d1a] 	LoadError: cannot load such file -- /home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/rdkit/Code/lib/RDKitChem

 DEBUG [54da2d1a] 	/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `require_relative'

/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `<top (required)>'

/var/www/chemotion_ELN/releases/20200503174904/config/application.rb:18:in `<top (required)>'

/var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `require'

/var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `<top (required)>'

/home/production/.rvm/gems/ruby-2.5.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

/home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `eval'

/home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `<main>'

 DEBUG [54da2d1a] 	(See full trace by running task with --trace)

removing tmp files..
removing tmp repo..
An error has occured
** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [f39b2619] Finished in 2.334 seconds with exit status 0 (successful).

  INFO The Gemfile's dependencies are satisfied, skipping installation

  INFO [deploy:migrate] Run `rake db:migrate`

 DEBUG [70435082] Running if test ! -d /var/www/chemotion_ELN/releases/20200503174904; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20200503174904'" 1>&2; false; fi as production@localhost

 DEBUG [70435082] Command: if test ! -d /var/www/chemotion_ELN/releases/20200503174904; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20200503174904'" 1>&2; false; fi

 DEBUG [087bae83] Finished in 0.042 seconds with exit status 0 (successful).

  INFO [5c8b6d67] Running /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.5.6 do bundle exec rake db:migrate as production@localhost

 DEBUG [5c8b6d67] Command: cd /var/www/chemotion_ELN/releases/20200503174904 && ( export NODE_VERSION="v12.16.1" RAILS_ENV="production" ; /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.5.6 do bundle exec rake db:migrate )

 DEBUG [54da2d1a] 	Now using node v12.16.1 (npm v6.13.7)

 DEBUG [54da2d1a] 	rake aborted!

 DEBUG [54da2d1a] 	LoadError: cannot load such file -- /home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/rdkit/Code/lib/RDKitChem

 DEBUG [54da2d1a] 	/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `require_relative'

/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib/rdkit_chem.rb:1:in `<top (required)>'

/var/www/chemotion_ELN/releases/20200503174904/config/application.rb:18:in `<top (required)>'

/var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `require'

/var/www/chemotion_ELN/releases/20200503174904/Rakefile:4:in `<top (required)>'

/home/production/.rvm/gems/ruby-2.5.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

/home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `eval'

/home/production/.rvm/gems/ruby-2.5.6/bin/ruby_executable_hooks:24:in `<main>'

 DEBUG [54da2d1a] 	(See full trace by running task with --trace)

removing tmp files..
removing tmp repo..
An error has occured
```

</details>

It appears that 
`/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/rdkit/Code/lib/RDKitChem`

is not a valid path, as the lib directory does not exist in this directory, but is instead found at the path:

`/home/production/.rvm/gems/ruby-2.5.6/bundler/gems/rdkit_chem-6777f2b2c749/lib`

I don't understand enough whether this is an issue with the script or my set up, so any advice would be appreciated. I checked the other closed issue that talked about issues with the installation script but this doesn't appear to be the same thing?

Thanks

**Comment by PiTrem** [comment]
Hi @jdnicholas,

it could be the rdkit_chem gem failed to compile properly and it thus missing some files.
The gem needs some [deb packages to be installed beforehand ](https://github.com/CamAnNguyen/rdkit_chem#prerequisites)  but it should have been done through running the script.

Also we have updated the version of the gem  because of an issue ( https://github.com/CamAnNguyen/rdkit_chem/commit/51cf8c5fb81af7af4a1605c6c9ffd5a5eed9c245 ).
I tested the installation script on a ubuntu18.04 with the latest chemotion_ELN revision (https://github.com/ComPlat/chemotion_ELN/commit/09b147e583a7394fd0a9dc011942a33e71753a27 )
Let me know if running the script again ( from [part 8](https://github.com/ComPlat/chemotion_ELN/blob/development/scripts/install_production.sh#L56) )works for you.

**Comment by jdnicholas** [comment]
Hi @PiTrem, thanks for that, running the script again now worked for me, everything is now up and running.

Thanks a lot!
