### ISSUE TITLE
A bug during editing a reaction

### ISSUE THREAD

**Issue by roma28** [ComPlat/chemotion_ELN#366]
When I'm trying to edit an existing reaction it just goes into infinite updating. If I manually refresh the page none of changes are saved. I've recorded this:
[youtube](https://www.youtube.com/watch?v=G4MLZJH0WGY)

**Comment by PiTrem** [comment]
Which revision of the code are you using ( commit hash in the last line of /var/www/chemotion_ELN/revision.log) ?

Could you check the last lines of the application log when you try to update the reaction.
Using tail :
`tail -f /var/www/chemotion_ELN/shared/log/production.log `

**Comment by roma28** [comment]
I'm running ubuntu 20.04. `tails` gives this:
```
2020-09-07 11:26:55 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:26:55 +0000 
2020-09-07 11:26:58 +0000, [INFO]: Started GET "/api/v1/reactions.json?collection_id=3&page=1&per_page=15&&filter_created_at=false" for 127.0.0.1 at 2020-09-07 11:26:58 +0000 
2020-09-07 11:27:01 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:01 +0000 
2020-09-07 11:27:01 +0000, [INFO]: Started GET "/api/v1/reactions/7.json" for 127.0.0.1 at 2020-09-07 11:27:01 +0000 
2020-09-07 11:27:02 +0000, [INFO]: Started GET "/api/v1/literatures?element_type=reaction&element_id=7" for 127.0.0.1 at 2020-09-07 11:27:02 +0000 
2020-09-07 11:27:07 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:07 +0000 
2020-09-07 11:27:13 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:13 +0000 
2020-09-07 11:27:19 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:19 +0000 
2020-09-07 11:27:19 +0000, [INFO]: Started GET "/api/v1/inbox?cnt_only=false" for 127.0.0.1 at 2020-09-07 11:27:19 +0000 
2020-09-07 11:27:25 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:25 +0000 
2020-09-07 11:27:31 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:31 +0000 
2020-09-07 11:27:43 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:43 +0000 
2020-09-07 11:27:45 +0000, [INFO]: Started GET "/api/v1/reactions/7.json" for 127.0.0.1 at 2020-09-07 11:27:45 +0000 
2020-09-07 11:27:46 +0000, [INFO]: Started GET "/api/v1/literatures?element_type=reaction&element_id=7" for 127.0.0.1 at 2020-09-07 11:27:46 +0000 
2020-09-07 11:27:49 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:49 +0000 
2020-09-07 11:27:55 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:27:55 +0000 
2020-09-07 11:28:01 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:28:01 +0000 
2020-09-07 11:28:07 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:28:07 +0000 
2020-09-07 11:28:13 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:28:13 +0000 
2020-09-07 11:31:46 +0000, [INFO]: Started GET "/mydb/collection/3/reaction/7" for 127.0.0.1 at 2020-09-07 11:31:46 +0000 
2020-09-07 11:31:46 +0000, [INFO]: Processing by PagesController#welcome as HTML 
2020-09-07 11:31:46 +0000, [INFO]:   Parameters: {"any"=>"collection/3/reaction/7"} 
2020-09-07 11:31:46 +0000, [INFO]:   Rendered pages/welcome.haml within layouts/application (0.1ms) 
2020-09-07 11:31:46 +0000, [INFO]: Completed 200 OK in 2ms (Views: 1.8ms | ActiveRecord: 0.0ms) 
2020-09-07 11:31:48 +0000, [INFO]: Started GET "/api/v1/users/current.json" for 127.0.0.1 at 2020-09-07 11:31:48 +0000 
2020-09-07 11:31:48 +0000, [INFO]: Started GET "/api/v1/collections/locked.json" for 127.0.0.1 at 2020-09-07 11:31:48 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/collections/roots.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/collections/shared_roots.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/collections/remote_roots.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/inbox?cnt_only=true" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/syncCollections/sync_remote_roots.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/ols_terms/list.json?name=rxno&edited=true" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/ols_terms/list.json?name=chmo&edited=true" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/profiles.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/collections/3" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/users/current.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/reactions/7.json" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:49 +0000, [INFO]: Started GET "/api/v1/ui/initialize" for 127.0.0.1 at 2020-09-07 11:31:49 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/users/current.json" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/messages/config.json" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/users/current.json" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/samples.json?collection_id=3&page=1&per_page=15&&filter_created_at=true&product_only=false&molecule_sort=0" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/reactions.json?collection_id=3&page=1&per_page=15&&filter_created_at=true" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/wellplates.json?collection_id=3&page=1&per_page=15&&filter_created_at=true" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/screens.json?collection_id=3&page=1&per_page=15&&filter_created_at=true" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/research_plans.json?collection_id=3&page=1&per_page=15&&filter_created_at=true" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/images/favicon.ico" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:50 +0000, [FATAL]:  | ActionController::RoutingError (No route matches [GET] "/images/favicon.ico"): |   actionpack (4.2.11.3) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call' |   actionpack (4.2.11.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' |   railties (4.2.11.3) lib/rails/rack/logger.rb:38:in `call_app' |   railties (4.2.11.3) lib/rails/rack/logger.rb:20:in `block in call' |   activesupport (4.2.11.3) lib/active_support/tagged_logging.rb:68:in `block in tagged' |   activesupport (4.2.11.3) lib/active_support/tagged_logging.rb:26:in `tagged' |   activesupport (4.2.11.3) lib/active_support/tagged_logging.rb:68:in `tagged' |   railties (4.2.11.3) lib/rails/rack/logger.rb:20:in `call' |   actionpack (4.2.11.3) lib/action_dispatch/middleware/request_id.rb:21:in `call' |   rack (1.6.13) lib/rack/methodoverride.rb:22:in `call' |   rack (1.6.13) lib/rack/runtime.rb:18:in `call' |   activesupport (4.2.11.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' |   actionpack (4.2.11.3) lib/action_dispatch/middleware/static.rb:120:in `call' |   actionpack (4.2.11.3) lib/action_dispatch/middleware/static.rb:120:in `call' |   rack (1.6.13) lib/rack/sendfile.rb:113:in `call' |   railties (4.2.11.3) lib/rails/engine.rb:518:in `call' |   railties (4.2.11.3) lib/rails/application.rb:165:in `call' |   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request' |   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request' |   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop' |   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads' |   /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception' |  |  
2020-09-07 11:31:50 +0000, [INFO]: Started GET "/api/v1/literatures?element_type=reaction&element_id=7" for 127.0.0.1 at 2020-09-07 11:31:50 +0000 
2020-09-07 11:31:53 +0000, [INFO]: [ActiveJob] Enqueued PubchemCidJob (Job ID: 5a486cd7-661c-4df9-a8f3-5b979f0adfef) to DelayedJob(pubchem) 
2020-09-07 11:31:53 +0000, [INFO]: [ActiveJob] Enqueued PubchemLcssJob (Job ID: a5f07714-389d-425f-ae69-822fb604234f) to DelayedJob(pubchemLcss) 
2020-09-07 11:31:53 +0000, [INFO]: [ActiveJob] Enqueued RefreshElementTagJob (Job ID: 733d7c4f-9c6d-4822-9f44-6ab67cd0efeb) to DelayedJob(refresh_element_tag) 
2020-09-07 11:31:53 +0000, [INFO]: [ActiveJob] Enqueued ChemrepoIdJob (Job ID: 21888910-443b-4ef5-8412-299ea204a402) to DelayedJob(chemrepo_id_job) 
2020-09-07 11:31:53 +0000, [ERROR]: Could not load configuration. No such file - /var/www/chemotion_ELN/releases/20200906171511/config/editors.yml 
2020-09-07 11:31:53 +0000, [ERROR]: Could not load configuration. No such file - /var/www/chemotion_ELN/releases/20200906171511/config/user_props.yml 
2020-09-07 11:31:56 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:31:56 +0000 
2020-09-07 11:32:02 +0000, [INFO]: Started GET "/api/v1/messages/list.json?is_ack=0" for 127.0.0.1 at 2020-09-07 11:32:02 +0000 
```

I've opened the reaction, edited it, clicked "Save", waited and refreshed page.

**Comment by PiTrem** [comment]
the issue appeared with switching from ruby 2.5 to 2.6.   
A fix will be released later today.

**Comment by PiTrem** [comment]
The code has been updated. 9ea75212f9 should have fixed the issue.

**Comment by roma28** [comment]
Looks like the bug is fixed.
