### ISSUE TITLE
Browserslist: caniuse-lite is outdated and Cannot find module '@novnc/noVNC/lib/rfb'

### ISSUE THREAD

**Issue by sneumann** [ComPlat/chemotion_ELN#380]
Hi, 
I am playing with the dockerised chemotion. I get the messages below, and I think I have 
two separate issues: 1) `Browserslist: caniuse-lite is outdated`  and `Cannot find module '@novnc/noVNC/lib/rfb'`
I'd need a quick heads-up if that might be an issue in the container, or me starting the whole thing. 
Thanks in advance, 
yours, 
Steffen

```
...
rake aborted!
BrowserifyRails::BrowserifyError: Error while running `/home/app/chemotion_ELN/node_modules/.bin/browserify -t [ babelify --presets [ @babel/preset-env  @babel/preset-react ] --plugins [ @babel/plugin-proposal-object-rest-spread ] ] -g uglifyify  --list -o "/home/app/chemotion_ELN/tmp/cache/browserify-rails/output20210310-569-n7ls79" -`:

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Can't walk dependency graph: Cannot find module '@novnc/noVNC/lib/rfb' from '/home/app/chemotion_ELN/app/assets/javascripts/libCnC/CnC.js'
    required by /home/app/chemotion_ELN/app/assets/javascripts/libCnC/CnC.js
    at /home/app/chemotion_ELN/node_modules/browser-resolve/node_modules/resolve/lib/async.js:115:35
    at processDirs (/home/app/chemotion_ELN/node_modules/browser-resolve/node_modules/resolve/lib/async.js:268:39)
    at isdir (/home/app/chemotion_ELN/node_modules/browser-resolve/node_modules/resolve/lib/async.js:275:32)
    at /home/app/chemotion_ELN/node_modules/browser-resolve/node_modules/resolve/lib/async.js:25:69
    at FSReqWrap.oncomplete (fs.js:152:21)
/home/app/chemotion_ELN/app/assets/config/manifest.js:3
```

**Comment by PiTrem** [comment]
Hi Steffen,

npm  packages have to be lowercase (for a few years already). However a combination of older package and npm version can work or has been working.
We have just updated this part with the newer novnc package and [the correct import path](https://github.com/ComPlat/chemotion_ELN/commit/e0f55b949d875026ea714a101e20674ae443b8a8).
