### ISSUE TITLE
docker-compose method of settting up development environment fails

### ISSUE THREAD

**Issue by sphuber** [ComPlat/chemotion_ELN#382]
I am trying to set up a development environment using Docker. Following the [instructions found here](https://eln.chemotion.net/chemotionsaurus/docs/eln/docker_installation) I manage to initialize the database container, however, at the next step to install dependencies missing from the container, an error is raised.

The problem is with executing this command
```
docker-compose run app /bin/bash -c 'source /usr/local/nvm/nvm.sh;\
 cd node_modules/@novnc/noVNC;\
 npx babel-upgrade --write; npm i; npm i pako; npm i @babel/preset-env;\
 mkdir -p utils;\
 curl https://raw.githubusercontent.com/novnc/noVNC/master/utils/use_require.js > utils/use_require.js;\
 node utils/use_require.js --clean; true'
```
The output is as follows:
```
WARNING: Found orphan containers (build_db_data_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting build_postgres_1 ... done
Starting build_sftp_1     ... done
/bin/bash: line 1: cd: node_modules/@novnc/noVNC: No such file or directory
🙌  Thanks for trying out https://github.com/babel/babel-upgrade !

Updating .babelrc config at .babelrc
Index: .babelrc
===================================================================
--- .babelrc	Before Upgrade
+++ .babelrc	After Upgrade


Updating closest package.json dependencies
Index: /home/app/chemotion_ELN/package.json
===================================================================
--- /home/app/chemotion_ELN/package.json	Before Upgrade
+++ /home/app/chemotion_ELN/package.json	After Upgrade
@@ -112,9 +112,9 @@
     ]
   },
   "devDependencies": {
     "@babel/register": "^7.11.5",
-    "babel-eslint": "7.2.2",
+    "babel-eslint": "^9.0.0",
     "enzyme": "^3.7.0",
     "enzyme-adapter-react-16": "^1.6.0",
     "eslint": "^4.19.1",
     "eslint-config-airbnb": "^16.1.0",


npm WARN deprecated babel-eslint@9.0.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN @citation-js/plugin-isbn@0.2.1 requires a peer of @citation-js/core@^0.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react-dom@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN qrcode.react@0.6.1 requires a peer of react@0.12 - 0.14 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-async-script-loader@0.3.0 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-input-autosize@1.1.0 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-svg-inline@1.2.0 requires a peer of react@^0.14.0 || ^15.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-spy-react@2.0.1 requires a peer of sinon@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@3.0.6 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1 package, removed 6 packages, updated 1 package and audited 1904 packages in 5.62s

67 packages are looking for funding
  run `npm fund` for details

found 29 vulnerabilities (25 low, 1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN @citation-js/plugin-isbn@0.2.1 requires a peer of @citation-js/core@^0.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react-dom@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN qrcode.react@0.6.1 requires a peer of react@0.12 - 0.14 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-async-script-loader@0.3.0 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-input-autosize@1.1.0 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-svg-inline@1.2.0 requires a peer of react@^0.14.0 || ^15.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-spy-react@2.0.1 requires a peer of sinon@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@3.0.6 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pako@2.0.3
added 1 package from 6 contributors, updated 1 package and audited 1905 packages in 6.378s

67 packages are looking for funding
  run `npm fund` for details

found 29 vulnerabilities (25 low, 1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN @citation-js/plugin-isbn@0.2.1 requires a peer of @citation-js/core@^0.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN chem-spectra-client@0.10.10 requires a peer of react-dom@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN qrcode.react@0.6.1 requires a peer of react@0.12 - 0.14 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-async-script-loader@0.3.0 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-input-autosize@1.1.0 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@3.2.0 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-svg-inline@1.2.0 requires a peer of react@^0.14.0 || ^15.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ui-tree@3.1.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-spy-react@2.0.1 requires a peer of sinon@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@3.0.6 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @babel/preset-env@7.13.10
added 286 packages from 14 contributors, removed 10 packages, updated 63 packages, moved 2 packages and audited 2181 packages in 14.593s

67 packages are looking for funding
  run `npm fund` for details

found 29 vulnerabilities (25 low, 1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5103  100  5103    0     0  15187      0 --:--:-- --:--:-- --:--:-- 15187
Removing /home/app/chemotion_ELN/lib
Writing /home/app/chemotion_ELN/lib/vendor/assets/javascripts/autocomplete.min.js
Failure converting modules: Error: ENOENT: no such file or directory, scandir '/home/app/chemotion_ELN/core'
```
I think the failure message at the bottom is problematic, because the next command that is suggested to verify the installation
```
docker-compose run app rake ketcherails:import:common_templates
```
fails as well:
```
WARNING: Found orphan containers (build_db_data_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting build_sftp_1     ... done
Starting build_postgres_1 ... done
rake aborted!
NameError: uninitialized constant OnelineLogFormatter
/home/app/chemotion_ELN/config/environments/production.rb:85:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/railtie.rb:210:in `instance_eval'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/railtie.rb:210:in `configure'
/home/app/chemotion_ELN/config/environments/production.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/engine.rb:597:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/engine.rb:597:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/application.rb:352:in `initialize!'
/home/app/chemotion_ELN/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.5.5/gems/railties-4.2.11.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.5.5/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => ketcherails:import:common_templates => environment
(See full trace by running task with --trace)
```

Any suggestions on how to debug this would be much appreciated

**Comment by PiTrem** [comment]
Thx,
[Instructions](https://github.com/ComPlat/chemotion_saurus/commits/master/docs/eln/docker-installation.md) have been updated
