### ISSUE TITLE
Migration is broken

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#656]
The following migration is broken: `20210527172347_add_solvent_to_samples.rb`
line 9, `sample.update_column` should be `item.update_column`.
In addition, after fixing it, this happens:

```
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 1, expected 2)
/chemotion/app/db/migrate/20210527172347_add_solvent_to_samples.rb:9:in `block in change'
/chemotion/app/db/migrate/20210527172347_add_solvent_to_samples.rb:6:in `change'

Caused by:
ArgumentError: wrong number of arguments (given 1, expected 2)
/chemotion/app/db/migrate/20210527172347_add_solvent_to_samples.rb:9:in `block in change'
/chemotion/app/db/migrate/20210527172347_add_solvent_to_samples.rb:6:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by PiTrem** [comment]
time  heals everything
or almost
