### ISSUE TITLE
HyperLinksSection error in reaction

### ISSUE THREAD

**Issue by phuang26** [ComPlat/chemotion_ELN#995]
ELN v1.4.0

"hyperlinks"=>"[\"file://xxxxxxx/xx16%1234%201.1.RAW\"]"}, 

Error message:
`TypeError: t.map is not a function
    at r.renderHyperLinkList (HyperLinksSection.js:69:20)
    at r.render (HyperLinksSection.js:123:17)
    at Wa (react-dom.production.min.js:187:188)
    at Za (react-dom.production.min.js:186:173)
    at Ys (react-dom.production.min.js:269:427)
    at xl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at Vl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
`

**Comment by phuang26** [comment]
fixed with PR: https://github.com/ComPlat/chemotion_ELN/pull/1002

**Comment by phuang26** [comment]
merged to ELN v1.4.1
